server:
  port: 8899
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.springframework: DEBUG

resource:
  host: ${GATEWAY_HOST:http://localhost:8000}
  path: /resources/{0}
  content-type: "audio/mpeg"

song:
  host: ${GATEWAY_HOST:http://localhost:8000}
  path: /songs

#############
# Messaging #
#############
spring:
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER:rmuser}
    password: ${RABBITMQ_DEFAULT_PASS:rmpassword}
  cloud:
    stream:
      function.definition: save;remove
      bindings:
        save-in-0:
          destination: uploaded
        remove-in-0:
          destination: removed
  application:
    name: resource-processor
  sleuth:
    propagation:
      type: B3,W3C
    opentracing:
      enabled: true
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:9411/

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  
############
# Actuator #
############
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  tracing:
    sampling:
      probability: 1.0
